//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.HIS.Ngoaitru.CheckCard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiTheBHYT", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class ApiTheBHYT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maCSKCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngaySinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((this.gioiTinhField.Equals(value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hoTen {
            get {
                return this.hoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.hoTenField, value) != true)) {
                    this.hoTenField = value;
                    this.RaisePropertyChanged("hoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maCSKCB {
            get {
                return this.maCSKCBField;
            }
            set {
                if ((object.ReferenceEquals(this.maCSKCBField, value) != true)) {
                    this.maCSKCBField = value;
                    this.RaisePropertyChanged("maCSKCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maThe {
            get {
                return this.maTheField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheField, value) != true)) {
                    this.maTheField = value;
                    this.RaisePropertyChanged("maThe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayBD {
            get {
                return this.ngayBDField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayBDField, value) != true)) {
                    this.ngayBDField = value;
                    this.RaisePropertyChanged("ngayBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayKT {
            get {
                return this.ngayKTField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayKTField, value) != true)) {
                    this.ngayKTField = value;
                    this.RaisePropertyChanged("ngayKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((object.ReferenceEquals(this.ngaySinhField, value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KQNhanLichSuKCBBS", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class KQNhanLichSuKCBBS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cqBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VMS.HIS.Ngoaitru.CheckCard.LichSuKCB2018[] dsLichSuKCB2018Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VMS.HIS.Ngoaitru.CheckCard.LichSuKT2018[] dsLichSuKT2018Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ghiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maDKBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKetQuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maSoBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheCuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayDu5NamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngaySinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cqBHXH {
            get {
                return this.cqBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.cqBHXHField, value) != true)) {
                    this.cqBHXHField = value;
                    this.RaisePropertyChanged("cqBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VMS.HIS.Ngoaitru.CheckCard.LichSuKCB2018[] dsLichSuKCB2018 {
            get {
                return this.dsLichSuKCB2018Field;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKCB2018Field, value) != true)) {
                    this.dsLichSuKCB2018Field = value;
                    this.RaisePropertyChanged("dsLichSuKCB2018");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VMS.HIS.Ngoaitru.CheckCard.LichSuKT2018[] dsLichSuKT2018 {
            get {
                return this.dsLichSuKT2018Field;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKT2018Field, value) != true)) {
                    this.dsLichSuKT2018Field = value;
                    this.RaisePropertyChanged("dsLichSuKT2018");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ghiChu {
            get {
                return this.ghiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.ghiChuField, value) != true)) {
                    this.ghiChuField = value;
                    this.RaisePropertyChanged("ghiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.gioiTinhField, value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDen {
            get {
                return this.gtTheDenField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenField, value) != true)) {
                    this.gtTheDenField = value;
                    this.RaisePropertyChanged("gtTheDen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDenMoi {
            get {
                return this.gtTheDenMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenMoiField, value) != true)) {
                    this.gtTheDenMoiField = value;
                    this.RaisePropertyChanged("gtTheDenMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTu {
            get {
                return this.gtTheTuField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuField, value) != true)) {
                    this.gtTheTuField = value;
                    this.RaisePropertyChanged("gtTheTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTuMoi {
            get {
                return this.gtTheTuMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuMoiField, value) != true)) {
                    this.gtTheTuMoiField = value;
                    this.RaisePropertyChanged("gtTheTuMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hoTen {
            get {
                return this.hoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.hoTenField, value) != true)) {
                    this.hoTenField = value;
                    this.RaisePropertyChanged("hoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maDKBD {
            get {
                return this.maDKBDField;
            }
            set {
                if ((object.ReferenceEquals(this.maDKBDField, value) != true)) {
                    this.maDKBDField = value;
                    this.RaisePropertyChanged("maDKBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKV {
            get {
                return this.maKVField;
            }
            set {
                if ((object.ReferenceEquals(this.maKVField, value) != true)) {
                    this.maKVField = value;
                    this.RaisePropertyChanged("maKV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKetQua {
            get {
                return this.maKetQuaField;
            }
            set {
                if ((object.ReferenceEquals(this.maKetQuaField, value) != true)) {
                    this.maKetQuaField = value;
                    this.RaisePropertyChanged("maKetQua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maSoBHXH {
            get {
                return this.maSoBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.maSoBHXHField, value) != true)) {
                    this.maSoBHXHField = value;
                    this.RaisePropertyChanged("maSoBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maThe {
            get {
                return this.maTheField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheField, value) != true)) {
                    this.maTheField = value;
                    this.RaisePropertyChanged("maThe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheCu {
            get {
                return this.maTheCuField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheCuField, value) != true)) {
                    this.maTheCuField = value;
                    this.RaisePropertyChanged("maTheCu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheMoi {
            get {
                return this.maTheMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheMoiField, value) != true)) {
                    this.maTheMoiField = value;
                    this.RaisePropertyChanged("maTheMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloi {
            get {
                return this.maloiField;
            }
            set {
                if ((object.ReferenceEquals(this.maloiField, value) != true)) {
                    this.maloiField = value;
                    this.RaisePropertyChanged("maloi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayDu5Nam {
            get {
                return this.ngayDu5NamField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayDu5NamField, value) != true)) {
                    this.ngayDu5NamField = value;
                    this.RaisePropertyChanged("ngayDu5Nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((object.ReferenceEquals(this.ngaySinhField, value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKCB2018", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKCB2018 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kqDieuTriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maCSKCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long maHoSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayRaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayVaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenBenhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kqDieuTri {
            get {
                return this.kqDieuTriField;
            }
            set {
                if ((object.ReferenceEquals(this.kqDieuTriField, value) != true)) {
                    this.kqDieuTriField = value;
                    this.RaisePropertyChanged("kqDieuTri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maCSKCB {
            get {
                return this.maCSKCBField;
            }
            set {
                if ((object.ReferenceEquals(this.maCSKCBField, value) != true)) {
                    this.maCSKCBField = value;
                    this.RaisePropertyChanged("maCSKCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long maHoSo {
            get {
                return this.maHoSoField;
            }
            set {
                if ((this.maHoSoField.Equals(value) != true)) {
                    this.maHoSoField = value;
                    this.RaisePropertyChanged("maHoSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayRa {
            get {
                return this.ngayRaField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayRaField, value) != true)) {
                    this.ngayRaField = value;
                    this.RaisePropertyChanged("ngayRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayVao {
            get {
                return this.ngayVaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayVaoField, value) != true)) {
                    this.ngayVaoField = value;
                    this.RaisePropertyChanged("ngayVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenBenh {
            get {
                return this.tenBenhField;
            }
            set {
                if ((object.ReferenceEquals(this.tenBenhField, value) != true)) {
                    this.tenBenhField = value;
                    this.RaisePropertyChanged("tenBenh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.tinhTrangField, value) != true)) {
                    this.tinhTrangField = value;
                    this.RaisePropertyChanged("tinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKT2018", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKT2018 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maLoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thoiGianKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thongBaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userKTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maLoi {
            get {
                return this.maLoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maLoiField, value) != true)) {
                    this.maLoiField = value;
                    this.RaisePropertyChanged("maLoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thoiGianKT {
            get {
                return this.thoiGianKTField;
            }
            set {
                if ((object.ReferenceEquals(this.thoiGianKTField, value) != true)) {
                    this.thoiGianKTField = value;
                    this.RaisePropertyChanged("thoiGianKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thongBao {
            get {
                return this.thongBaoField;
            }
            set {
                if ((object.ReferenceEquals(this.thongBaoField, value) != true)) {
                    this.thongBaoField = value;
                    this.RaisePropertyChanged("thongBao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userKT {
            get {
                return this.userKTField;
            }
            set {
                if ((object.ReferenceEquals(this.userKTField, value) != true)) {
                    this.userKTField = value;
                    this.RaisePropertyChanged("userKT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KQNhanLichSuKCB", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class KQNhanLichSuKCB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cqBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VMS.HIS.Ngoaitru.CheckCard.LichSuKCB[] dsLichSuKCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VMS.HIS.Ngoaitru.CheckCard.LichSuKiemTra[] dsLichSuKiemTraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ghiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maDKBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKetQuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maSoBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheCuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayDu5NamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngaySinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cqBHXH {
            get {
                return this.cqBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.cqBHXHField, value) != true)) {
                    this.cqBHXHField = value;
                    this.RaisePropertyChanged("cqBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VMS.HIS.Ngoaitru.CheckCard.LichSuKCB[] dsLichSuKCB {
            get {
                return this.dsLichSuKCBField;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKCBField, value) != true)) {
                    this.dsLichSuKCBField = value;
                    this.RaisePropertyChanged("dsLichSuKCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VMS.HIS.Ngoaitru.CheckCard.LichSuKiemTra[] dsLichSuKiemTra {
            get {
                return this.dsLichSuKiemTraField;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKiemTraField, value) != true)) {
                    this.dsLichSuKiemTraField = value;
                    this.RaisePropertyChanged("dsLichSuKiemTra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ghiChu {
            get {
                return this.ghiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.ghiChuField, value) != true)) {
                    this.ghiChuField = value;
                    this.RaisePropertyChanged("ghiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.gioiTinhField, value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDen {
            get {
                return this.gtTheDenField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenField, value) != true)) {
                    this.gtTheDenField = value;
                    this.RaisePropertyChanged("gtTheDen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDenMoi {
            get {
                return this.gtTheDenMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenMoiField, value) != true)) {
                    this.gtTheDenMoiField = value;
                    this.RaisePropertyChanged("gtTheDenMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTu {
            get {
                return this.gtTheTuField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuField, value) != true)) {
                    this.gtTheTuField = value;
                    this.RaisePropertyChanged("gtTheTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTuMoi {
            get {
                return this.gtTheTuMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuMoiField, value) != true)) {
                    this.gtTheTuMoiField = value;
                    this.RaisePropertyChanged("gtTheTuMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hoTen {
            get {
                return this.hoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.hoTenField, value) != true)) {
                    this.hoTenField = value;
                    this.RaisePropertyChanged("hoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maDKBD {
            get {
                return this.maDKBDField;
            }
            set {
                if ((object.ReferenceEquals(this.maDKBDField, value) != true)) {
                    this.maDKBDField = value;
                    this.RaisePropertyChanged("maDKBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKV {
            get {
                return this.maKVField;
            }
            set {
                if ((object.ReferenceEquals(this.maKVField, value) != true)) {
                    this.maKVField = value;
                    this.RaisePropertyChanged("maKV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKetQua {
            get {
                return this.maKetQuaField;
            }
            set {
                if ((object.ReferenceEquals(this.maKetQuaField, value) != true)) {
                    this.maKetQuaField = value;
                    this.RaisePropertyChanged("maKetQua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maSoBHXH {
            get {
                return this.maSoBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.maSoBHXHField, value) != true)) {
                    this.maSoBHXHField = value;
                    this.RaisePropertyChanged("maSoBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maThe {
            get {
                return this.maTheField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheField, value) != true)) {
                    this.maTheField = value;
                    this.RaisePropertyChanged("maThe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheCu {
            get {
                return this.maTheCuField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheCuField, value) != true)) {
                    this.maTheCuField = value;
                    this.RaisePropertyChanged("maTheCu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheMoi {
            get {
                return this.maTheMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheMoiField, value) != true)) {
                    this.maTheMoiField = value;
                    this.RaisePropertyChanged("maTheMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloi {
            get {
                return this.maloiField;
            }
            set {
                if ((object.ReferenceEquals(this.maloiField, value) != true)) {
                    this.maloiField = value;
                    this.RaisePropertyChanged("maloi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayDu5Nam {
            get {
                return this.ngayDu5NamField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayDu5NamField, value) != true)) {
                    this.ngayDu5NamField = value;
                    this.RaisePropertyChanged("ngayDu5Nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((object.ReferenceEquals(this.ngaySinhField, value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKCB", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKCB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kqDieuTriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maCSKCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long maHoSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayRaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayVaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenBenhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kqDieuTri {
            get {
                return this.kqDieuTriField;
            }
            set {
                if ((object.ReferenceEquals(this.kqDieuTriField, value) != true)) {
                    this.kqDieuTriField = value;
                    this.RaisePropertyChanged("kqDieuTri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maCSKCB {
            get {
                return this.maCSKCBField;
            }
            set {
                if ((object.ReferenceEquals(this.maCSKCBField, value) != true)) {
                    this.maCSKCBField = value;
                    this.RaisePropertyChanged("maCSKCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long maHoSo {
            get {
                return this.maHoSoField;
            }
            set {
                if ((this.maHoSoField.Equals(value) != true)) {
                    this.maHoSoField = value;
                    this.RaisePropertyChanged("maHoSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayRa {
            get {
                return this.ngayRaField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayRaField, value) != true)) {
                    this.ngayRaField = value;
                    this.RaisePropertyChanged("ngayRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayVao {
            get {
                return this.ngayVaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayVaoField, value) != true)) {
                    this.ngayVaoField = value;
                    this.RaisePropertyChanged("ngayVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenBenh {
            get {
                return this.tenBenhField;
            }
            set {
                if ((object.ReferenceEquals(this.tenBenhField, value) != true)) {
                    this.tenBenhField = value;
                    this.RaisePropertyChanged("tenBenh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.tinhTrangField, value) != true)) {
                    this.tinhTrangField = value;
                    this.RaisePropertyChanged("tinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKiemTra", Namespace="http://schemas.datacontract.org/2004/07/BHXH_CheckThe.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKiemTra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maLoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thoiGianKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thongBaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userKTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maLoi {
            get {
                return this.maLoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maLoiField, value) != true)) {
                    this.maLoiField = value;
                    this.RaisePropertyChanged("maLoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thoiGianKT {
            get {
                return this.thoiGianKTField;
            }
            set {
                if ((object.ReferenceEquals(this.thoiGianKTField, value) != true)) {
                    this.thoiGianKTField = value;
                    this.RaisePropertyChanged("thoiGianKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thongBao {
            get {
                return this.thongBaoField;
            }
            set {
                if ((object.ReferenceEquals(this.thongBaoField, value) != true)) {
                    this.thongBaoField = value;
                    this.RaisePropertyChanged("thongBao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userKT {
            get {
                return this.userKTField;
            }
            set {
                if ((object.ReferenceEquals(this.userKTField, value) != true)) {
                    this.userKTField = value;
                    this.RaisePropertyChanged("userKT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckCard.ILichSuKCB")]
    public interface ILichSuKCB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILichSuKCB/KiemTraTheBh_366", ReplyAction="http://tempuri.org/ILichSuKCB/KiemTraTheBh_366Response")]
        VMS.HIS.Ngoaitru.CheckCard.KQNhanLichSuKCBBS KiemTraTheBh_366(VMS.HIS.Ngoaitru.CheckCard.ApiTheBHYT apiTheBhyt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILichSuKCB/KiemTraTheBh_595", ReplyAction="http://tempuri.org/ILichSuKCB/KiemTraTheBh_595Response")]
        VMS.HIS.Ngoaitru.CheckCard.KQNhanLichSuKCB KiemTraTheBh_595(VMS.HIS.Ngoaitru.CheckCard.ApiTheBHYT apiTheBhyt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILichSuKCBChannel : VMS.HIS.Ngoaitru.CheckCard.ILichSuKCB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LichSuKCBClient : System.ServiceModel.ClientBase<VMS.HIS.Ngoaitru.CheckCard.ILichSuKCB>, VMS.HIS.Ngoaitru.CheckCard.ILichSuKCB {
        
        public LichSuKCBClient() {
        }
        
        public LichSuKCBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LichSuKCBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LichSuKCBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LichSuKCBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VMS.HIS.Ngoaitru.CheckCard.KQNhanLichSuKCBBS KiemTraTheBh_366(VMS.HIS.Ngoaitru.CheckCard.ApiTheBHYT apiTheBhyt) {
            return base.Channel.KiemTraTheBh_366(apiTheBhyt);
        }
        
        public VMS.HIS.Ngoaitru.CheckCard.KQNhanLichSuKCB KiemTraTheBh_595(VMS.HIS.Ngoaitru.CheckCard.ApiTheBHYT apiTheBhyt) {
            return base.Channel.KiemTraTheBh_595(apiTheBhyt);
        }
    }
}
