//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VMS.HIS.QMSScreen.QMSService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback VmsQmsLaysoQMSGoilaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback VmsQmsLaydanhsachbenhnhanchokhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetQMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback QMSPhongkham_getOperationCompleted;
        
        private System.Threading.SendOrPostCallback QMSPhongkham_CapnhatTrangthaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusQmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSoKhamQmsChucNangOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNoiThucHienOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQMSInforOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeQMSStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteQMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeQMSPriorityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListQmSbyMaPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListQmSbyMaPhongAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertGoiLoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetNoiThucHienOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::VMS.HIS.QMSScreen.Properties.Settings.Default.VMS_HIS_Qms_QMSService_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event VmsQmsLaysoQMSGoilaiCompletedEventHandler VmsQmsLaysoQMSGoilaiCompleted;
        
        /// <remarks/>
        public event VmsQmsLaydanhsachbenhnhanchokhamCompletedEventHandler VmsQmsLaydanhsachbenhnhanchokhamCompleted;
        
        /// <remarks/>
        public event ResetQMSCompletedEventHandler ResetQMSCompleted;
        
        /// <remarks/>
        public event QMSPhongkham_getCompletedEventHandler QMSPhongkham_getCompleted;
        
        /// <remarks/>
        public event QMSPhongkham_CapnhatTrangthaiCompletedEventHandler QMSPhongkham_CapnhatTrangthaiCompleted;
        
        /// <remarks/>
        public event UpdateStatusQmsCompletedEventHandler UpdateStatusQmsCompleted;
        
        /// <remarks/>
        public event GetSoKhamQmsChucNangCompletedEventHandler GetSoKhamQmsChucNangCompleted;
        
        /// <remarks/>
        public event GetNoiThucHienCompletedEventHandler GetNoiThucHienCompleted;
        
        /// <remarks/>
        public event getQMSInforCompletedEventHandler getQMSInforCompleted;
        
        /// <remarks/>
        public event ChangeQMSStatusCompletedEventHandler ChangeQMSStatusCompleted;
        
        /// <remarks/>
        public event DeleteQMSCompletedEventHandler DeleteQMSCompleted;
        
        /// <remarks/>
        public event ChangeQMSPriorityCompletedEventHandler ChangeQMSPriorityCompleted;
        
        /// <remarks/>
        public event GetListQmSbyMaPhongCompletedEventHandler GetListQmSbyMaPhongCompleted;
        
        /// <remarks/>
        public event GetListQmSbyMaPhongAllCompletedEventHandler GetListQmSbyMaPhongAllCompleted;
        
        /// <remarks/>
        public event InsertGoiLoaCompletedEventHandler InsertGoiLoaCompleted;
        
        /// <remarks/>
        public event _GetNoiThucHienCompletedEventHandler _GetNoiThucHienCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VmsQmsLaysoQMSGoilai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable VmsQmsLaysoQMSGoilai(string maquay, string makhoa, string loaiqms) {
            object[] results = this.Invoke("VmsQmsLaysoQMSGoilai", new object[] {
                        maquay,
                        makhoa,
                        loaiqms});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void VmsQmsLaysoQMSGoilaiAsync(string maquay, string makhoa, string loaiqms) {
            this.VmsQmsLaysoQMSGoilaiAsync(maquay, makhoa, loaiqms, null);
        }
        
        /// <remarks/>
        public void VmsQmsLaysoQMSGoilaiAsync(string maquay, string makhoa, string loaiqms, object userState) {
            if ((this.VmsQmsLaysoQMSGoilaiOperationCompleted == null)) {
                this.VmsQmsLaysoQMSGoilaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVmsQmsLaysoQMSGoilaiOperationCompleted);
            }
            this.InvokeAsync("VmsQmsLaysoQMSGoilai", new object[] {
                        maquay,
                        makhoa,
                        loaiqms}, this.VmsQmsLaysoQMSGoilaiOperationCompleted, userState);
        }
        
        private void OnVmsQmsLaysoQMSGoilaiOperationCompleted(object arg) {
            if ((this.VmsQmsLaysoQMSGoilaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VmsQmsLaysoQMSGoilaiCompleted(this, new VmsQmsLaysoQMSGoilaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VmsQmsLaydanhsachbenhnhanchokham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable VmsQmsLaydanhsachbenhnhanchokham(string MaPhongKham, string makhoa, int sluong_hthi) {
            object[] results = this.Invoke("VmsQmsLaydanhsachbenhnhanchokham", new object[] {
                        MaPhongKham,
                        makhoa,
                        sluong_hthi});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void VmsQmsLaydanhsachbenhnhanchokhamAsync(string MaPhongKham, string makhoa, int sluong_hthi) {
            this.VmsQmsLaydanhsachbenhnhanchokhamAsync(MaPhongKham, makhoa, sluong_hthi, null);
        }
        
        /// <remarks/>
        public void VmsQmsLaydanhsachbenhnhanchokhamAsync(string MaPhongKham, string makhoa, int sluong_hthi, object userState) {
            if ((this.VmsQmsLaydanhsachbenhnhanchokhamOperationCompleted == null)) {
                this.VmsQmsLaydanhsachbenhnhanchokhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVmsQmsLaydanhsachbenhnhanchokhamOperationCompleted);
            }
            this.InvokeAsync("VmsQmsLaydanhsachbenhnhanchokham", new object[] {
                        MaPhongKham,
                        makhoa,
                        sluong_hthi}, this.VmsQmsLaydanhsachbenhnhanchokhamOperationCompleted, userState);
        }
        
        private void OnVmsQmsLaydanhsachbenhnhanchokhamOperationCompleted(object arg) {
            if ((this.VmsQmsLaydanhsachbenhnhanchokhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VmsQmsLaydanhsachbenhnhanchokhamCompleted(this, new VmsQmsLaydanhsachbenhnhanchokhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetQMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ResetQMS(long id, string MaQuay, int trang_thai) {
            this.Invoke("ResetQMS", new object[] {
                        id,
                        MaQuay,
                        trang_thai});
        }
        
        /// <remarks/>
        public void ResetQMSAsync(long id, string MaQuay, int trang_thai) {
            this.ResetQMSAsync(id, MaQuay, trang_thai, null);
        }
        
        /// <remarks/>
        public void ResetQMSAsync(long id, string MaQuay, int trang_thai, object userState) {
            if ((this.ResetQMSOperationCompleted == null)) {
                this.ResetQMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetQMSOperationCompleted);
            }
            this.InvokeAsync("ResetQMS", new object[] {
                        id,
                        MaQuay,
                        trang_thai}, this.ResetQMSOperationCompleted, userState);
        }
        
        private void OnResetQMSOperationCompleted(object arg) {
            if ((this.ResetQMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetQMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QMSPhongkham_get", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable QMSPhongkham_get(string maPhong, System.DateTime ngayTao, int trangThai, string makhoakcb) {
            object[] results = this.Invoke("QMSPhongkham_get", new object[] {
                        maPhong,
                        ngayTao,
                        trangThai,
                        makhoakcb});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void QMSPhongkham_getAsync(string maPhong, System.DateTime ngayTao, int trangThai, string makhoakcb) {
            this.QMSPhongkham_getAsync(maPhong, ngayTao, trangThai, makhoakcb, null);
        }
        
        /// <remarks/>
        public void QMSPhongkham_getAsync(string maPhong, System.DateTime ngayTao, int trangThai, string makhoakcb, object userState) {
            if ((this.QMSPhongkham_getOperationCompleted == null)) {
                this.QMSPhongkham_getOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQMSPhongkham_getOperationCompleted);
            }
            this.InvokeAsync("QMSPhongkham_get", new object[] {
                        maPhong,
                        ngayTao,
                        trangThai,
                        makhoakcb}, this.QMSPhongkham_getOperationCompleted, userState);
        }
        
        private void OnQMSPhongkham_getOperationCompleted(object arg) {
            if ((this.QMSPhongkham_getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QMSPhongkham_getCompleted(this, new QMSPhongkham_getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QMSPhongkham_CapnhatTrangthai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool QMSPhongkham_CapnhatTrangthai(long id_kham, long id, int trangThai, int qmstype) {
            object[] results = this.Invoke("QMSPhongkham_CapnhatTrangthai", new object[] {
                        id_kham,
                        id,
                        trangThai,
                        qmstype});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void QMSPhongkham_CapnhatTrangthaiAsync(long id_kham, long id, int trangThai, int qmstype) {
            this.QMSPhongkham_CapnhatTrangthaiAsync(id_kham, id, trangThai, qmstype, null);
        }
        
        /// <remarks/>
        public void QMSPhongkham_CapnhatTrangthaiAsync(long id_kham, long id, int trangThai, int qmstype, object userState) {
            if ((this.QMSPhongkham_CapnhatTrangthaiOperationCompleted == null)) {
                this.QMSPhongkham_CapnhatTrangthaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQMSPhongkham_CapnhatTrangthaiOperationCompleted);
            }
            this.InvokeAsync("QMSPhongkham_CapnhatTrangthai", new object[] {
                        id_kham,
                        id,
                        trangThai,
                        qmstype}, this.QMSPhongkham_CapnhatTrangthaiOperationCompleted, userState);
        }
        
        private void OnQMSPhongkham_CapnhatTrangthaiOperationCompleted(object arg) {
            if ((this.QMSPhongkham_CapnhatTrangthaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QMSPhongkham_CapnhatTrangthaiCompleted(this, new QMSPhongkham_CapnhatTrangthaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateStatusQms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateStatusQms(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai) {
            object[] results = this.Invoke("UpdateStatusQms", new object[] {
                        patientCode,
                        maPhong,
                        ngayTao,
                        trangThai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusQmsAsync(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai) {
            this.UpdateStatusQmsAsync(patientCode, maPhong, ngayTao, trangThai, null);
        }
        
        /// <remarks/>
        public void UpdateStatusQmsAsync(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai, object userState) {
            if ((this.UpdateStatusQmsOperationCompleted == null)) {
                this.UpdateStatusQmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusQmsOperationCompleted);
            }
            this.InvokeAsync("UpdateStatusQms", new object[] {
                        patientCode,
                        maPhong,
                        ngayTao,
                        trangThai}, this.UpdateStatusQmsOperationCompleted, userState);
        }
        
        private void OnUpdateStatusQmsOperationCompleted(object arg) {
            if ((this.UpdateStatusQmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusQmsCompleted(this, new UpdateStatusQmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSoKhamQmsChucNang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSoKhamQmsChucNang(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai) {
            object[] results = this.Invoke("GetSoKhamQmsChucNang", new object[] {
                        patientCode,
                        maPhong,
                        ngayTao,
                        trangThai});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSoKhamQmsChucNangAsync(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai) {
            this.GetSoKhamQmsChucNangAsync(patientCode, maPhong, ngayTao, trangThai, null);
        }
        
        /// <remarks/>
        public void GetSoKhamQmsChucNangAsync(string patientCode, string maPhong, System.DateTime ngayTao, int trangThai, object userState) {
            if ((this.GetSoKhamQmsChucNangOperationCompleted == null)) {
                this.GetSoKhamQmsChucNangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSoKhamQmsChucNangOperationCompleted);
            }
            this.InvokeAsync("GetSoKhamQmsChucNang", new object[] {
                        patientCode,
                        maPhong,
                        ngayTao,
                        trangThai}, this.GetSoKhamQmsChucNangOperationCompleted, userState);
        }
        
        private void OnGetSoKhamQmsChucNangOperationCompleted(object arg) {
            if ((this.GetSoKhamQmsChucNangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSoKhamQmsChucNangCompleted(this, new GetSoKhamQmsChucNangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNoiThucHien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetNoiThucHien() {
            object[] results = this.Invoke("GetNoiThucHien", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetNoiThucHienAsync() {
            this.GetNoiThucHienAsync(null);
        }
        
        /// <remarks/>
        public void GetNoiThucHienAsync(object userState) {
            if ((this.GetNoiThucHienOperationCompleted == null)) {
                this.GetNoiThucHienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNoiThucHienOperationCompleted);
            }
            this.InvokeAsync("GetNoiThucHien", new object[0], this.GetNoiThucHienOperationCompleted, userState);
        }
        
        private void OnGetNoiThucHienOperationCompleted(object arg) {
            if ((this.GetNoiThucHienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNoiThucHienCompleted(this, new GetNoiThucHienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQMSInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getQMSInfor(string patientcode, string maphong) {
            object[] results = this.Invoke("getQMSInfor", new object[] {
                        patientcode,
                        maphong});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getQMSInforAsync(string patientcode, string maphong) {
            this.getQMSInforAsync(patientcode, maphong, null);
        }
        
        /// <remarks/>
        public void getQMSInforAsync(string patientcode, string maphong, object userState) {
            if ((this.getQMSInforOperationCompleted == null)) {
                this.getQMSInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQMSInforOperationCompleted);
            }
            this.InvokeAsync("getQMSInfor", new object[] {
                        patientcode,
                        maphong}, this.getQMSInforOperationCompleted, userState);
        }
        
        private void OngetQMSInforOperationCompleted(object arg) {
            if ((this.getQMSInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQMSInforCompleted(this, new getQMSInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeQMSStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeQMSStatus(string patientcode, string maphong, string machucnang, string makhoa, byte _type) {
            object[] results = this.Invoke("ChangeQMSStatus", new object[] {
                        patientcode,
                        maphong,
                        machucnang,
                        makhoa,
                        _type});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeQMSStatusAsync(string patientcode, string maphong, string machucnang, string makhoa, byte _type) {
            this.ChangeQMSStatusAsync(patientcode, maphong, machucnang, makhoa, _type, null);
        }
        
        /// <remarks/>
        public void ChangeQMSStatusAsync(string patientcode, string maphong, string machucnang, string makhoa, byte _type, object userState) {
            if ((this.ChangeQMSStatusOperationCompleted == null)) {
                this.ChangeQMSStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeQMSStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeQMSStatus", new object[] {
                        patientcode,
                        maphong,
                        machucnang,
                        makhoa,
                        _type}, this.ChangeQMSStatusOperationCompleted, userState);
        }
        
        private void OnChangeQMSStatusOperationCompleted(object arg) {
            if ((this.ChangeQMSStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeQMSStatusCompleted(this, new ChangeQMSStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteQMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteQMS(int QMSID) {
            object[] results = this.Invoke("DeleteQMS", new object[] {
                        QMSID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteQMSAsync(int QMSID) {
            this.DeleteQMSAsync(QMSID, null);
        }
        
        /// <remarks/>
        public void DeleteQMSAsync(int QMSID, object userState) {
            if ((this.DeleteQMSOperationCompleted == null)) {
                this.DeleteQMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteQMSOperationCompleted);
            }
            this.InvokeAsync("DeleteQMS", new object[] {
                        QMSID}, this.DeleteQMSOperationCompleted, userState);
        }
        
        private void OnDeleteQMSOperationCompleted(object arg) {
            if ((this.DeleteQMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteQMSCompleted(this, new DeleteQMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeQMSPriority", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeQMSPriority(string patientcode, string maphong, byte tthai) {
            object[] results = this.Invoke("ChangeQMSPriority", new object[] {
                        patientcode,
                        maphong,
                        tthai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeQMSPriorityAsync(string patientcode, string maphong, byte tthai) {
            this.ChangeQMSPriorityAsync(patientcode, maphong, tthai, null);
        }
        
        /// <remarks/>
        public void ChangeQMSPriorityAsync(string patientcode, string maphong, byte tthai, object userState) {
            if ((this.ChangeQMSPriorityOperationCompleted == null)) {
                this.ChangeQMSPriorityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeQMSPriorityOperationCompleted);
            }
            this.InvokeAsync("ChangeQMSPriority", new object[] {
                        patientcode,
                        maphong,
                        tthai}, this.ChangeQMSPriorityOperationCompleted, userState);
        }
        
        private void OnChangeQMSPriorityOperationCompleted(object arg) {
            if ((this.ChangeQMSPriorityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeQMSPriorityCompleted(this, new ChangeQMSPriorityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListQmSbyMaPhong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetListQmSbyMaPhong(string maPhong, string machucnang, System.DateTime ngayTao, int trangThai, string maKhoa) {
            object[] results = this.Invoke("GetListQmSbyMaPhong", new object[] {
                        maPhong,
                        machucnang,
                        ngayTao,
                        trangThai,
                        maKhoa});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetListQmSbyMaPhongAsync(string maPhong, string machucnang, System.DateTime ngayTao, int trangThai, string maKhoa) {
            this.GetListQmSbyMaPhongAsync(maPhong, machucnang, ngayTao, trangThai, maKhoa, null);
        }
        
        /// <remarks/>
        public void GetListQmSbyMaPhongAsync(string maPhong, string machucnang, System.DateTime ngayTao, int trangThai, string maKhoa, object userState) {
            if ((this.GetListQmSbyMaPhongOperationCompleted == null)) {
                this.GetListQmSbyMaPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListQmSbyMaPhongOperationCompleted);
            }
            this.InvokeAsync("GetListQmSbyMaPhong", new object[] {
                        maPhong,
                        machucnang,
                        ngayTao,
                        trangThai,
                        maKhoa}, this.GetListQmSbyMaPhongOperationCompleted, userState);
        }
        
        private void OnGetListQmSbyMaPhongOperationCompleted(object arg) {
            if ((this.GetListQmSbyMaPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListQmSbyMaPhongCompleted(this, new GetListQmSbyMaPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListQmSbyMaPhongAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetListQmSbyMaPhongAll() {
            object[] results = this.Invoke("GetListQmSbyMaPhongAll", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetListQmSbyMaPhongAllAsync() {
            this.GetListQmSbyMaPhongAllAsync(null);
        }
        
        /// <remarks/>
        public void GetListQmSbyMaPhongAllAsync(object userState) {
            if ((this.GetListQmSbyMaPhongAllOperationCompleted == null)) {
                this.GetListQmSbyMaPhongAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListQmSbyMaPhongAllOperationCompleted);
            }
            this.InvokeAsync("GetListQmSbyMaPhongAll", new object[0], this.GetListQmSbyMaPhongAllOperationCompleted, userState);
        }
        
        private void OnGetListQmSbyMaPhongAllOperationCompleted(object arg) {
            if ((this.GetListQmSbyMaPhongAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListQmSbyMaPhongAllCompleted(this, new GetListQmSbyMaPhongAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertGoiLoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertGoiLoa(string soKham, string quayGoi, string mayGoi, string maKhoa, int trangThai, byte loaiQMS, string nguoiTao, System.DateTime ngayTao, string mayTao, string loaGoi, string noiDung) {
            this.Invoke("InsertGoiLoa", new object[] {
                        soKham,
                        quayGoi,
                        mayGoi,
                        maKhoa,
                        trangThai,
                        loaiQMS,
                        nguoiTao,
                        ngayTao,
                        mayTao,
                        loaGoi,
                        noiDung});
        }
        
        /// <remarks/>
        public void InsertGoiLoaAsync(string soKham, string quayGoi, string mayGoi, string maKhoa, int trangThai, byte loaiQMS, string nguoiTao, System.DateTime ngayTao, string mayTao, string loaGoi, string noiDung) {
            this.InsertGoiLoaAsync(soKham, quayGoi, mayGoi, maKhoa, trangThai, loaiQMS, nguoiTao, ngayTao, mayTao, loaGoi, noiDung, null);
        }
        
        /// <remarks/>
        public void InsertGoiLoaAsync(string soKham, string quayGoi, string mayGoi, string maKhoa, int trangThai, byte loaiQMS, string nguoiTao, System.DateTime ngayTao, string mayTao, string loaGoi, string noiDung, object userState) {
            if ((this.InsertGoiLoaOperationCompleted == null)) {
                this.InsertGoiLoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertGoiLoaOperationCompleted);
            }
            this.InvokeAsync("InsertGoiLoa", new object[] {
                        soKham,
                        quayGoi,
                        mayGoi,
                        maKhoa,
                        trangThai,
                        loaiQMS,
                        nguoiTao,
                        ngayTao,
                        mayTao,
                        loaGoi,
                        noiDung}, this.InsertGoiLoaOperationCompleted, userState);
        }
        
        private void OnInsertGoiLoaOperationCompleted(object arg) {
            if ((this.InsertGoiLoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertGoiLoaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetNoiThucHien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable _GetNoiThucHien() {
            object[] results = this.Invoke("_GetNoiThucHien", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void _GetNoiThucHienAsync() {
            this._GetNoiThucHienAsync(null);
        }
        
        /// <remarks/>
        public void _GetNoiThucHienAsync(object userState) {
            if ((this._GetNoiThucHienOperationCompleted == null)) {
                this._GetNoiThucHienOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetNoiThucHienOperationCompleted);
            }
            this.InvokeAsync("_GetNoiThucHien", new object[0], this._GetNoiThucHienOperationCompleted, userState);
        }
        
        private void On_GetNoiThucHienOperationCompleted(object arg) {
            if ((this._GetNoiThucHienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetNoiThucHienCompleted(this, new _GetNoiThucHienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VmsQmsLaysoQMSGoilaiCompletedEventHandler(object sender, VmsQmsLaysoQMSGoilaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VmsQmsLaysoQMSGoilaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VmsQmsLaysoQMSGoilaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VmsQmsLaydanhsachbenhnhanchokhamCompletedEventHandler(object sender, VmsQmsLaydanhsachbenhnhanchokhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VmsQmsLaydanhsachbenhnhanchokhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VmsQmsLaydanhsachbenhnhanchokhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ResetQMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void QMSPhongkham_getCompletedEventHandler(object sender, QMSPhongkham_getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QMSPhongkham_getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QMSPhongkham_getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void QMSPhongkham_CapnhatTrangthaiCompletedEventHandler(object sender, QMSPhongkham_CapnhatTrangthaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QMSPhongkham_CapnhatTrangthaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QMSPhongkham_CapnhatTrangthaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateStatusQmsCompletedEventHandler(object sender, UpdateStatusQmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusQmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusQmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSoKhamQmsChucNangCompletedEventHandler(object sender, GetSoKhamQmsChucNangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSoKhamQmsChucNangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSoKhamQmsChucNangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetNoiThucHienCompletedEventHandler(object sender, GetNoiThucHienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNoiThucHienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNoiThucHienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getQMSInforCompletedEventHandler(object sender, getQMSInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQMSInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQMSInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ChangeQMSStatusCompletedEventHandler(object sender, ChangeQMSStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeQMSStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeQMSStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteQMSCompletedEventHandler(object sender, DeleteQMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteQMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteQMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ChangeQMSPriorityCompletedEventHandler(object sender, ChangeQMSPriorityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeQMSPriorityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeQMSPriorityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListQmSbyMaPhongCompletedEventHandler(object sender, GetListQmSbyMaPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListQmSbyMaPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListQmSbyMaPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListQmSbyMaPhongAllCompletedEventHandler(object sender, GetListQmSbyMaPhongAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListQmSbyMaPhongAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListQmSbyMaPhongAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertGoiLoaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void _GetNoiThucHienCompletedEventHandler(object sender, _GetNoiThucHienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetNoiThucHienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetNoiThucHienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591