//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.QMS.TTS.TTS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TTS.ITTS")]
    public interface ITTS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITTS/SaveAudio", ReplyAction="http://tempuri.org/ITTS/SaveAudioResponse")]
        byte[] SaveAudio(string noidung, ref string fileName, ref string messge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITTS/DeleteFile", ReplyAction="http://tempuri.org/ITTS/DeleteFileResponse")]
        void DeleteFile();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITTSChannel : VMS.QMS.TTS.TTS.ITTS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TTSClient : System.ServiceModel.ClientBase<VMS.QMS.TTS.TTS.ITTS>, VMS.QMS.TTS.TTS.ITTS {
        
        public TTSClient() {
        }
        
        public TTSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TTSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TTSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TTSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] SaveAudio(string noidung, ref string fileName, ref string messge) {
            return base.Channel.SaveAudio(noidung, ref fileName, ref messge);
        }
        
        public void DeleteFile() {
            base.Channel.DeleteFile();
        }
    }
}
